require('dotenv').config();
const AWS = require('aws-sdk');
const Card = require('vcards-js');

const { BUCKET_NAME, IAM_USER_KEY, IAM_USER_SECRET } = process.env;

const vCard = new Card();
const s3 = new AWS.S3({
  accessKeyId: IAM_USER_KEY,
  secretAccessKey: IAM_USER_SECRET,
  Bucket: BUCKET_NAME,
});

// const contactInfo: {
//   firstName: 'Jeff',
//   middleName: 'M',
//   lastName: 'Arcel',
//   organization: 'ACME Corporation',
//   workPhone: '248-259-2871',
//   birthday: new Date('10-29-1984'),
//   title: 'Software Developer',
//   url: 'https://github.com/jarcel',
//   note: 'Generated by short.card (https://short.card)',
// };

const makeCard = (req, res) => {
  const { contactInfo } = req.body;
  // Set properties
  Object.keys(contactInfo).map((objectKey) => {
    vCard[objectKey] = contactInfo[objectKey];
  });

  const file = {
    name: `${Math.random().toString(25).slice(2)}.vcf`,
    data: vCard.getFormattedString(),
  };

  const params = {
    Bucket: BUCKET_NAME,
    Key: file.name,
    Body: file.data,
    ACL: 'public-read',
  };

  const uploadCard = s3.upload(params).promise();
  uploadCard
    // Add listing to DB
    .then((data) => {
      console.log(`Success: ${data.Location}`);
      return data;
    })
    // Return short URL and Token
    .then(data => res.status(200).json({
      success: true,
      url: data.Location,
    }))
    .catch((err) => {
      console.log(`Error: ${err}`);
    });
};

module.exports = makeCard;
